/*!
 * File generated by platform wizard. DO NOT MODIFY
 *
 */

metaonly module Platform inherits xdc.platform.IPlatform {

    config ti.platforms.generic.Platform.Instance CPU =
        ti.platforms.generic.Platform.create("CPU", {
            clockRate:      432,                                       
            catalogName:    "ti.catalog.c6000",
            deviceName:     "TMS320C6748",
            externalMemoryMap: 
           [          
                ["E_RAM_CS2", 
                     {
                        name: "E_RAM_CS2",
                        base: 0x60000000,                    
                        len: 0x01000000,                    
                        space: "io",
                        access: "RW",
                     }
                ],
                ["E_RAM_CS3", 
                     {
                        name: "E_RAM_CS3",
                        base: 0x62000000,                    
                        len: 0x01000000,                    
                        space: "io",
                        access: "RW",
                     }
                ],
                ["E_RAM_CS4", 
                     {
                        name: "E_RAM_CS4",
                        base: 0x64000000,                    
                        len: 0x01000000,                    
                        space: "io",
                        access: "RW",
                     }
                ],
                ["E_RAM_CS5", 
                     {
                        name: "E_RAM_CS5",
                        base: 0x66000000,                    
                        len: 0x01000000,                    
                        space: "io",
                        access: "RW",
                     }
                ],
                ["SN_PAR", 
                     {
                        name: "SN_PAR",
                        base: 0xC0000000,                    
                        len: 0x00180000,                    
                        space: "data",
                        access: "RW",
                     }
                ],
                ["DDR2_SN_PAR4", 
                     {
                        name: "DDR2_SN_PAR4",
                        base: 0xC0180000,                    
                        len: 0x00080000,                    
                        space: "data",
                        access: "RW",
                     }
                ],
                ["DDR2_RAM", 
                     {
                        name: "DDR2_RAM",
                        base: 0xC0200000,                    
                        len: 0x02D00000,                    
                        space: "data",
                        access: "RW",
                     }
                ],
                ["DDR2_USB", 
                     {
                        name: "DDR2_USB",
                        base: 0xC2F00000,                    
                        len: 0x00100000,                    
                        space: "data",
                        access: "RW",
                     }
                ],
                ["App_Prog_START", 
                     {
                        name: "App_Prog_START",
                        base: 0xC3000000,                    
                        len: 0x00000400,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["DDR", 
                     {
                        name: "DDR",
                        base: 0xC3000400,                    
                        len: 0x000FF000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["Inf1", 
                     {
                        name: "Inf1",
                        base: 0xC30FF400,                    
                        len: 0x00000100,                    
                        space: "data",
                        access: "RW",
                     }
                ],
                ["Inf2", 
                     {
                        name: "Inf2",
                        base: 0xC30FF500,                    
                        len: 0x00000100,                    
                        space: "data",
                        access: "RW",
                     }
                ],
                ["Inf3", 
                     {
                        name: "Inf3",
                        base: 0xC30FF600,                    
                        len: 0x00000100,                    
                        space: "data",
                        access: "RW",
                     }
                ],
                ["Inf4", 
                     {
                        name: "Inf4",
                        base: 0xC30FF700,                    
                        len: 0x00000100,                    
                        space: "data",
                        access: "RW",
                     }
                ],
                ["Inf5", 
                     {
                        name: "Inf5",
                        base: 0xC30FF800,                    
                        len: 0x00000800,                    
                        space: "data",
                        access: "RW",
                     }
                ],
                ["DDR_EXT", 
                     {
                        name: "DDR_EXT",
                        base: 0xC4000000,                    
                        len: 0x0C000000,                    
                        space: "data",
                        access: "RW",
                     }
                ],
           ],
          l2Mode:"256k",
          l1PMode:"32k",
          l1DMode:"32k",

    });
    
instance :
    
    override config string codeMemory  = "DDR";   
    override config string dataMemory  = "DDR";                                
    override config string stackMemory = "L3_CBA_RAM";
    
}
